export const SET_POSITION = "SET_POSITION";
export const TOGGLE_ISS_LOCATION = "TOGGLE_ISS_LOCATION";
export const TOGGLE_USER_LOCATION = "TOGGLE_USER_LOCATION";

export const SET_HUMANS = "SET_HUMANS";

export const SET_NAME = 'SET_NAME';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PROFILE_PICTURE = 'SET_PROFILE_PICTURE';